"""empty message

Revision ID: 464de4c921db
Revises: None
Create Date: 2016-07-22 17:44:52.532423

"""

# revision identifiers, used by Alembic.
revision = '464de4c921db'
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('key', sa.String(length=32), nullable=False),
                    sa.Column('perm_jury', sa.Boolean(), nullable=False),
                    sa.Column('perm_master', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('problems',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('test_cases', sa.Integer(), nullable=False),
                    sa.Column('time_limit', sa.Float(), nullable=False),
                    sa.Column('memory_limit', sa.Integer(), nullable=False),
                    sa.Column('generator_code', sa.UnicodeText(), nullable=False),
                    sa.Column('generator_language', sa.Unicode(length=10), nullable=False),
                    sa.Column('grader_code', sa.UnicodeText(), nullable=False),
                    sa.Column('grader_language', sa.Unicode(length=10), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('jobs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gid', sa.Integer(), nullable=True),
                    sa.Column('problem_id', sa.Integer(), nullable=False),
                    sa.Column('creation_time', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Enum('queued', 'cancelled', 'started', 'finished', name='jobstatus'),
                              nullable=False),
                    sa.Column('claim_time', sa.DateTime(), nullable=True),
                    sa.Column('completion_time', sa.DateTime(), nullable=True),
                    sa.Column('code', sa.UnicodeText(), nullable=False),
                    sa.Column('language', sa.Unicode(length=10), nullable=False),
                    sa.Column('verification_code', sa.Integer(), nullable=True),
                    sa.Column('verdict',
                              sa.Enum('accepted', 'ran', 'wrong_answer', 'time_limit_exceeded', 'memory_limit_exceeded',
                                      'runtime_error', 'illegal_syscall', 'compilation_error', 'judge_error',
                                      name='jobverdict'), nullable=True),
                    sa.Column('last_ran_case', sa.Integer(), nullable=True),
                    sa.Column('execution_time', sa.Float(), nullable=True),
                    sa.Column('execution_memory', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_jobs_claim_time'), 'jobs', ['claim_time'], unique=False)
    op.create_index(op.f('ix_jobs_completion_time'), 'jobs', ['completion_time'], unique=False)
    op.create_index(op.f('ix_jobs_creation_time'), 'jobs', ['creation_time'], unique=False)
    op.create_index(op.f('ix_jobs_gid'), 'jobs', ['gid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_gid'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_creation_time'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_completion_time'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_claim_time'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('problems')
    op.drop_table('apikeys')
    ### end Alembic commands ###
