"""Add `reader` permission

Revision ID: 85158bfe8859
Revises: e59a88c0ca1b
Create Date: 2017-01-28 22:33:00.816045

"""

# revision identifiers, used by Alembic.
revision = '85158bfe8859'
down_revision = 'e59a88c0ca1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('perm_reader', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'perm_reader')
    ### end Alembic commands ###
