"""Submissions system

Revision ID: ddc7b6ac327f
Revises: f45c7466228d
Create Date: 2016-08-19 14:40:06.976423

"""

# revision identifiers, used by Alembic.
revision = 'ddc7b6ac327f'
down_revision = 'f45c7466228d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.drop_index('ix_jobs_gid', table_name='jobs')
    op.drop_constraint('jobs_ibfk_1', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'submissions', ['submission_id'], ['id'])
    op.drop_column('jobs', 'code')
    op.drop_column('jobs', 'gid')
    op.drop_column('jobs', 'language')
    op.drop_column('jobs', 'problem_id')
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('problem_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('language', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('jobs', sa.Column('gid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('code', mysql.TEXT(), nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_ibfk_1', 'jobs', 'problems', ['problem_id'], ['id'])
    op.create_index('ix_jobs_gid', 'jobs', ['gid'], unique=False)
    op.drop_column('jobs', 'submission_id')
    op.drop_table('submissions')
    ### end Alembic commands ###
