"""empty message

Revision ID: e59a88c0ca1b
Revises: ddc7b6ac327f
Create Date: 2016-11-11 13:53:43.213502

"""

# revision identifiers, used by Alembic.
revision = 'e59a88c0ca1b'
down_revision = 'ddc7b6ac327f'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('gid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'gid')
    ### end Alembic commands ###
