"""empty message

Revision ID: f45c7466228d
Revises: 464de4c921db
Create Date: 2016-07-23 12:10:03.089016

"""

# revision identifiers, used by Alembic.
revision = 'f45c7466228d'
down_revision = '464de4c921db'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('name', sa.Unicode(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'name')
    ### end Alembic commands ###
